
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Constants with fallbacks for instantiation
const SUPABASE_URL = "https://dczsjvcgjxqgjdihonfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjenNqdmNnanhxZ2pkaWhvbmZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODQyOTgsImV4cCI6MjA2MDk2MDI5OH0.X2nlf1EWQodx3XxDNoNVHcO3UdoKtMAD8pMiVSvAbik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enhanced client configuration with robust auth settings
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      // New settings for better security and error handling
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Debug mode off in production
      debug: import.meta.env.DEV,
    },
    global: {
      // Add headers for better traceability
      headers: {
        'X-Client-Info': 'math-game-web',
      },
    }
  }
);

// Add fallback error handling
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'SIGNED_OUT' || event === 'USER_DELETED') {
    // Clear any cached data on signout
    localStorage.removeItem('math_game_active_profile');
  }
});

// Export a function to get a fresh client if needed
export const getSupabaseClient = () => {
  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: true,
        flowType: 'pkce',
        debug: import.meta.env.DEV,
      },
    }
  );
};
